/*
    Names froms:
        - Player Handbook 5e
        - http://brandondraga.tumblr.com/post/66804468075/chris-perkins-npc-name-list
*/

const {
    randomFromList
} = Lib.helpers;

const dwarf_names = {
    title: 'Dwarf',

    generate: function (gender_names) {
        return randomFromList(gender_names) + ' (clan ' + randomFromList(this.clans) + ')';
    },

    male: [
        'Adrik',
        'Agaro',
        'Alberich',
        'Arnan',
        'Arval',
        'Auxlan',
        'Avamir',
        'Baelnar',
        'Baern',
        'Balfam',
        'Bariken',
        'Berend',
        'Brottor',
        'Bruenor',
        'Borkûl',
        'Dain',
        'Darrak',
        'Darkûl',
        'Delg',
        'Dolmen',
        'Dyrnar',
        'Eberk',
        'Einkil',
        'Erag',
        'Ezegan',
        'Fargrim',
        'Ferrek',
        'Flint',
        'Gardain',
        'Garmûl',
        'Glint',
        'Ghorvas',
        'Grimmalk',
        'Haeltar',
        'Hagan',
        'Halagmar',
        'Halzar',
        'Harbek',
        'Hlant',
        'Kildrak',
        'Korlag',
        'Krag',
        'Krim',
        'Kurman',
        'Lurtrum',
        'Malagar',
        'Mardam',
        'Maulnar',
        'Melgar',
        'Morak',
        'Morgran',
        'Orobok',
        'Orsik',
        'Oskar',
        'Radek',
        'Rangrim',
        'Rogath',
        'Roken',
        'Rozag',
        'Rurik',
        'Sabakzar',
        'Sharak',
        'Smethykk',
        'Swargar',
        'Taklinn',
        'Thoradin',
        'Thorbalt',
        'Thorfin',
        'Thorin',
        'Traubon',
        'Tredigar',
        'Tordek',
        'Travok',
        'Ulfgar',
        'Vabûl',
        'Veit',
        'Vistrum',
        'Vondal',
        'Wolvar'
    ],

    female: [
        'Amber',
        'Artin',
        'Audhild',
        'Bardryn',
        'Beyla',
        'Dagnal',
        'Diesa',
        'Eldeth',
        'Falkrunn',
        'Fenryl',
        'Finellen',
        'Freyde',
        'Grenenzel',
        'Gunnloda',
        'Gurdis',
        'Helja',
        'Ilde',
        'Kathra',
        'Kristryd',
        'Krystolari',
        'Liftrasa',
        'Lokara',
        'Lurka',
        'Mardred',
        'Marnia',
        'Praxana',
        'Riswynn',
        'Rokel',
        'Roksana',
        'Sannl',
        'Torbera',
        'Torgga',
        'Thurlfara',
        'Vauldra',
        'Veklani',
        'Vistra',
        'Vronwe',
        'Zebel'
    ],

    clans: [
        'Ambershard',
        'Balderk',
        'Barrelhelm',
        'Battlehammer',
        'Brawnanvil',
        'Copperhearth',
        'Dankil',
        'Deepmiddens',
        'Drakantal',
        'Evermead',
        'Fireforge',
        'Frostbeard',
        'Garkalan',
        'Gorunn',
        'Grimtor',
        'Hackshield',
        'Holderhek',
        'Ironfist',
        'Irongull',
        'Loderr',
        'Lutgehr',
        'Markolak',
        'Ramcrown',
        'Rockharvest',
        'Rumnaheim',
        'Silvertarn',
        'Skandalor',
        'Strakeln',
        'Torunn',
        'Ungart',
        'Zarkanan'
    ]
};

module.exports = dwarf_names;
