/*
    Names froms:
        - Player Handbook 5e
        - http://brandondraga.tumblr.com/post/66804468075/chris-perkins-npc-name-list
*/

const {
    percentage,
    randomFromList
} = Lib.helpers;


const elf_names = {
    title: 'Elf',

    generate: function (gender_names) {
        let name = '';
        if (percentage() < 33) {
            name = randomFromList(this.extra);
        } else {
            name = randomFromList(gender_names);
            if (percentage() < 20) {
                name += (' ' + randomFromList(this.extra));
            }
        }
        name += (' ' + randomFromList(this.surnames));
        return name;
    },

    male: [
        'Adran',
        'Aelar',
        'Alarcion',
        'Alathar',
        'Aramil',
        'Arannis',
        'Ariandar',
        'Arromar',
        'Aust',
        'Beiro',
        'Berrian',
        'Borel',
        'Bvachan',
        'Carric',
        'Carydion',
        'Callis',
        'Cyprian',
        'Dusan',
        'Elgoth',
        'Enialis',
        'Erdan',
        'Erevan',
        'Farlien',
        'Ferel',
        'Gaerlan',
        'Galinndan',
        'Gennal',
        'Hadarai',
        'Heian',
        'Himo',
        'Iafalior',
        'Immeral',
        'Ivellios',
        'Kaelthorn',
        'Laethan',
        'Leliar',
        'Leodor',
        'Lorak',
        'Lorifir',
        'Lucan',
        'Morian',
        'Miklos',
        'Oleran',
        'Peren',
        'Rolen',
        'Rylef',
        'Savian',
        'Seylas',
        'Soveliss',
        'Tevior',
        'Thamior',
        'Tharivol',
        'Theren',
        'Varis',
        'Veyas'
    ],

    female: [
        'Adrie',
        'Althaea',
        'Anastrianna',
        'Andraste',
        'Antinua',
        'Aryllan',
        'Atalya',
        'Ayrthwil',
        'Bethrynna',
        'Birel',
        'Caelynn',
        'Chaedi',
        'Clorinda',
        'Dara',
        'Drusilia',
        'Enna',
        'Faral',
        'Felosial',
        'Ielenia',
        'Irann',
        'Irva',
        'Jelenneth',
        'Keyleth',
        'Leshanna',
        'Lia',
        'Lyfalia',
        'Meriele',
        'Mialee',
        'Milena',
        'Naivara',
        'Olethea',
        'Quelenna',
        'Quillathe',
        'Ronefel',
        'Sariel',
        'Shanairra',
        'Shava',
        'Shayndel',
        'Theirastra',
        'Thia',
        'Thirya',
        'Vadania',
        'Valanthe',
        'Valna',
        'Velene',
        'Venefiq',
        'Zereni'
    ],

    surnames: [
        'Amakiir (Gemflower)',
        'Amastacia (Starflower)',
        'Autumnloft',
        'Balefrost',
        'Briarfell',
        'Evenwind',
        'Galanodel (Moonwhisper)',
        'Graytrails',
        'Holimion (Diamonddew)',
        'Ilphelkiir (Gemblossom)',
        'Liadon (Silverfrond)',
        'Meliamne (Oakenheel)',
        'Mooncairn',
        'Nailo (Nightbreeze)',
        'Riverwall',
        'Siannodel (Moonbrook)',
        'Stormwolf',
        'Summergale',
        'Sunshadow',
        'Woodenhawk',
        'Xiloscient (Goldpetal)'
    ],

    extra: [
        'Hadír',
        'Belecthan',
        'Sandir',
        'Dúndor',
        'Galadilion',
        'Celegûr',
        'Borongil',
        'Glonor',
        'Amrienor',
        'Andrel',
        'Thiras',
        'Athorfin',
        'Celeval',
        'Ilathriel',
        'Milduin',
        'Celevorn',
        'Berethir',
        'Golfalas',
        'Andel',
        'Nirwen',
        'Nirion',
        'Gundrel',
        'Úngor',
        'Ralfin',
        'Cíndor',
        'Aragil',
        'Elevreth',
        'Ethrion',
        'Emellion',
        'Anduin',
        'Glórendil',
        'Galaduil',
        'Filrion',
        'Galathrath',
        'Merchel',
        'Belegor',
        'Andronel',
        'Aglaril',
        'Araval',
        'Galathorn',
        'Daerondor',
        'Rimranion',
        'Duiril',
        'Endring',
        'Duinir',
        'Bregor',
        'Elweniel',
        'Angwil',
        'Thoronor',
        'Andrilion',
        'Gelduin',
        'Ethrond',
        'Arathor',
        'Núr',
        'Fingund',
        'Mirdor',
        'Ilathriel'
    ]
};

module.exports = elf_names;
