/*
    Names froms:
        - Player Handbook 5e
        - http://brandondraga.tumblr.com/post/66804468075/chris-perkins-npc-name-list
*/

const {
    randomFromList
} = Lib.helpers;

const human_names = {
    title: 'Human',

    generate: function (gender_names) {
        return randomFromList(gender_names) + ' ' + randomFromList(this.surnames);
    },

    male: [
        'Adler',
        'Admon',
        'Adolph',
        'Ahren',
        'Aiden',
        'Aimery',
        'Alain',
        'Alard',
        'Alaric',
        'Aldous',
        'Alek',
        'Alwyn',
        'Ambert',
        'Anlow',
        'Arando',
        'Benn',
        'Bram',
        'Bedrich',
        'Bertram',
        'Benvolio',
        'Bennett',
        'Brandis',
        'Cale',
        'Conrad',
        'Dalkon',
        'Daylen',
        'Dedric',
        'Del',
        'Derek',
        'Dexter',
        'Dian',
        'Dirke',
        'Dodd',
        'Donn',
        'Drew',
        'Dungarth',
        'Dyrk',
        'Eandro',
        'Erik',
        'Falken',
        'Feck',
        'Fenton',
        'Gallus',
        'Garvin',
        'Gregg',
        'Griswold',
        'Gryphero',
        'Hagar',
        'Hamlin',
        'Helmut',
        'Hew',
        'Jeras',
        'Jonn',
        'Kris',
        'Krynt',
        'Lavant',
        'Leyten',
        'Madian',
        'Malfier',
        'Marc',
        'Markus',
        'Meklan',
        'Mikal',
        'Milos',
        'Namen',
        'Navaren',
        'Nerle',
        'Nilus',
        'Ningyan',
        'Norris',
        'Phil',
        'Pieter',
        'Quentin',
        'Quinn',
        'Raeburn',
        'Raynard',
        'Regdar',
        'Ritter',
        'Rudolph',
        'Samm',
        'Semil',
        'Sevenson',
        'Steveren',
        'Talfen',
        'Tamond',
        'Taran',
        'Tavon',
        'Tegan',
        'Thom',
        'Vanan',
        'Vincent',
        'Wendell',
        'Wil',
        'Wolfram',
    ],

    female: [
        'Ana',
        'Azura',
        'Axelle',
        'Brey',
        'Brynna',
        'Carlen',
        'Cassi Clotilda',
        'Druella',
        'Eloise',
        'Eliska',
        'Eliza',
        'Enye',
        'Giselle',
        'Gwenn',
        'Hallan',
        'Jenn',
        'Kasaki',
        'Kat',
        'Kiera',
        'Lida',
        'Lorelei',
        'Luusi',
        'Megan',
        'Mika',
        'Millicent',
        'Mirabel',
        'Miri',
        'Natalie',
        'Nicola',
        'Nydia',
        'Pharana',
        'Remora',
        'Rolanda',
        'Rosalyn',
        'Rudelle',
        'Sachil',
        'Saidi',
        'Stasi',
        'Shawna',
        'Tanika',
        'Tura',
        'Tylsa',
        'Vencia',
        'Veronica',
        'Wilhelmina',
        'Xandrilla',
        'Zanne'
    ],

    surnames: [
        'Arkalis',
        'Armanci',
        'Baldric',
        'Ballard',
        'Bilger',
        'Blackstrand',
        'Brightwater',
        'Carnavon',
        'Caskajaro',
        'Coldshore',
        'Coyle',
        'Cresthill',
        'Cuttlescar',
        'Daargen',
        'Dalicarlia',
        'Danamark',
        'Donoghan',
        'Drumwind',
        'Dunhall',
        'Ereghast',
        'Falck',
        'Fallenbridge',
        'Faringray',
        'Fletcher',
        'Fryft',
        'Goldrudder',
        'Grantham',
        'Graylock',
        'Gullscream',
        'Hardy',
        'Hartman',
        'Hayward',
        'Hindergrass',
        'Iscalon',
        'Kreel',
        'Kroft',
        'Lamoth',
        'Leerstrom',
        'Lynchfield',
        'Moonridge',
        'Netheridge',
        'Oakenheart',
        'Pyncion',
        'Ratley',
        'Redraven',
        'Revenmar',
        'Roxley',
        'Rowland',
        'Sell',
        'Seratolva',
        'Shanks',
        'Shattermast',
        'Shaulfer',
        'Silvergraft',
        'Stavenger',
        'Stormchapel',
        'Strong',
        'Swiller',
        'Talandro ',
        'Targana',
        'Towerfall',
        'Umbermoor',
        'Van Devries',
        'Van Gandt',
        'Van Hyden',
        'Varcona',
        'Varzand',
        'Voortham',
        'Vrye',
        'Webb',
        'Welfer',
        'Wilxes',
        'Wintermere',
        'Wygarthe',
        'Zatchet',
        'Zethergyll'
    ]
};

module.exports = human_names;
